version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - CACHE_STORE=${CACHE_STORE}

  db:
    image: postgres:16
    container_name: postgres-laravel
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7-alpine
    container_name: redis-laravel
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: nginx-laravel
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  pgdata:
  redisdata: 